name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    # The type of runner that the job will run on
    # new
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
    - run:  docker-compose up -d
